name: drag_speed_dial
description: Flutter package to implement a FAB and dynamic Material Design Speed Dial, draggable, multi-directional children and much more.
version: 0.0.3
homepage: https://github.com/warrenrhodes/drag_speed_dial

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
